name: decipher
description: A scrible from you, and just for you. No one can decipher it. Only you.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Figtree
      fonts:
        - asset: assets/fonts/figtree/Figtree-Medium.ttf
        - asset: assets/fonts/figtree/Figtree-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/figtree/Figtree-Bold.ttf
          weight: 700
        - asset: assets/fonts/figtree/Figtree-MediumItalic.ttf
          style: italic

  uses-material-design: true

#  assets:
#    - assets/images


